baseURL = 'https://maverick.canhtran.me'
languageCode = 'es'
title = 'Colombiano anónimo'
theme = 'maverick'

[permalinks]
  pages = "/:slug"

[params]
  logo = '/assets/favicon.ico'
  description = "Noticias y temas relevantes en Colombia que probablemente no serán visibilizados por mas nadie, sea porque quienes lo saben tienen miedo a represalias, porque algún poder los silencia. En cualquier caso estas noticias o temas aparecen tergiversados en los medios oficiales, si es que aparecen."
  author = 'Anónimo'
  items = 10

  [params.comments]
    enabled = true
    githubRepo = 'canhtran/maverick'
    theme = 'github-light'

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = "-110"
  [[menu.main]]
    identifier = "posts"
    name = "Post"
    url = "/posts/"
    weight = -200

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokailight'
    tabWidth = 4

[taxonomies]
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "atom"

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"

ignoreErrors = ["error-remote-getjson"]
